# Generated by Django 5.2.17 on 2026-10-05 20:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('secure_token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('roll_no', models.CharField(db_index=True, help_text='e.g. 231MI001', max_length=30, unique=True, verbose_name='Roll Number')),
                ('branch', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Handle')),
                ('sig', models.CharField(choices=[('EC&P', 'EC&P'), ('Design', 'Design'), ('Website', 'Website'), ('Marketing', 'Marketing'), ('Media', 'Media')], max_length=50, verbose_name='Special Interest Group (SIG)')),
                ('previous_core', models.BooleanField(default=False, verbose_name='Previous Core Member')),
                ('y26_core', models.BooleanField(default=False, verbose_name='Part of Y26 Core')),
                ('learning_review', models.TextField(verbose_name='What have you learnt from the club?')),
                ('changes_review', models.TextField(verbose_name='What changes would you like to see or implement in the club?')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('contribution', models.TextField(verbose_name='Contribution / Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='members.member')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sig', models.CharField(choices=[('EC&P', 'EC&P'), ('Design', 'Design'), ('Website', 'Website'), ('Marketing', 'Marketing'), ('Media', 'Media')], max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sig', 'name'],
                'unique_together': {('name', 'sig')},
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_skills', to='members.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_members', to='members.skill')),
            ],
            options={
                'unique_together': {('member', 'skill')},
            },
        ),
    ]
