# Generated by Django 4.2.11 on 2026-10-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sig',
            field=models.CharField(max_length=255, verbose_name='Special Interest Group (SIG)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sig',
            field=models.CharField(choices=[('Website', 'Website'), ('Automation', 'Automation'), ('Electronics and Programming', 'Electronics and Programming'), ('Media', 'Media'), ('Marketing', 'Marketing')], max_length=50),
        ),
    ]
