# Generated by Django 4.2.11 on 2026-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_sig_alter_skill_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='sig',
            field=models.CharField(choices=[('Design', 'Design'), ('Website', 'Website'), ('Automation', 'Automation'), ('Electronics and Programming', 'Electronics and Programming'), ('Media', 'Media'), ('Marketing', 'Marketing')], max_length=50),
        ),
    ]
